### PR TITLE
add support for ignoring tcp sequence number and timestamp offset cha…

### PR DESCRIPTION
**Pull request by jegglest**
In order to simulate delayed packets, there are occasions where responses
to those packets need to be ignored insofar as they modify relative sequence
numbers or timestamps. For example a retransmitted SYN might be delayed until
after the TCP session ends, but a combination of bugs on the client and server
might result in the session persisting as if it never ended.

```
inbound injected packet:  0.100034 S 0:0(0) win 65535 <mss 1460,nop,wscale 6,sackOK,TS val 100 ecr 0>
outbound sniffed packet:  0.100083 S. 3079308609:3079308609(0) ack 1 win 65535 <mss 1460,nop,wscale 4,sackOK,TS val 3206488061 ecr 100>
inbound injected packet:  0.150127 . 1:101(100) ack 3079308610 win 1031 <nop,nop,TS val 150 ecr 3206488061>
outbound sniffed packet:  0.150170 . 3079308610:3079308610(0) ack 101 win 12495 <nop,nop,TS val 3206488111 ecr 150>
outbound sniffed packet:  0.150192 P. 3079308610:3079309010(400) ack 101 win 12501 <nop,nop,TS val 3206488111 ecr 150>
inbound injected packet:  0.200251 . 101:101(0) ack 3079309010 win 1024 <nop,nop,TS val 200 ecr 3206488111>
inbound injected packet:  0.200271 F. 101:101(0) ack 3079309010 win 1031 <nop,nop,TS val 200 ecr 3206488111>
outbound sniffed packet:  0.200287 . 3079309010:3079309010(0) ack 102 win 12501 <nop,nop,TS val 3206488161 ecr 200>
outbound sniffed packet:  0.200324 F. 3079309010:3079309010(0) ack 102 win 12501 <nop,nop,TS val 3206488161 ecr 200>
inbound injected packet:  0.250354 . 102:102(0) ack 3079309011 win 1031 <nop,nop,TS val 250 ecr 3206488161>
inbound injected packet:  0.265380 S 0:0(0) win 65535 <mss 1460,nop,wscale 6,sackOK,TS val 100 ecr 0>
outbound sniffed packet:  0.265402 S. 3079308609:3079308609(0) ack 1 win 65535 <mss 1460,nop,wscale 4,sackOK,TS val 3118763918 ecr 100>
inbound injected packet:  0.300437 . 1:1(0) ack 3079308610 win 1031 <nop,nop,TS val 150 ecr 3206488061>
outbound sniffed packet:  0.300455 R 3079308610:3079308610(0) win 0
```
```
 0.000 socket(..., SOCK_STREAM, IPPROTO_TCP) = 3
+0.000 setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
+0.000 bind(3, ..., ...) = 0
+0.000 listen(3, 1) = 0
+0.100 < S  0:0(0) win 65535 <mss 1460,nop,wscale 6,sackOK,TS val 100 ecr 0>
+0.000 > S. 0:0(0) ack 1 win 65535 <mss 1460,nop,wscale 4,sackOK,TS val 200 ecr 100>
+0.050 < . 1:101(100) ack 1 win 1031 <nop, nop, TS val 150 ecr 200>
+0.000 accept(3, ..., ...) = 4
+0.000 read(4, ..., 100) = 100
+0.000 write(4, ..., 400) = 400
+0.000 > . 1:1(0) ack 101 win 12495 <nop, nop, TS val 250 ecr 150>
+0.000 > P. 1:401(400) ack 101 win 12501 <nop, nop, TS val 250 ecr 150>
+0.050 < . 101:101(0) ack 401 win 1024 <nop, nop, TS val 200 ecr 250>
+0.000 < F. 101:101(0) ack 401 win 1031 <nop, nop, TS val 200 ecr 250>
+0.000 > . 401:401(0) ack 102 win 12501 <nop, nop, TS val 300 ecr 200>
+0.000 close(4) = 0
+0.000 > F. 401:401(0) ack 102 win 12501 <nop, nop, TS val 300 ecr 200>
+0.050 < . 102:102(0) ack 402 win 1031 <nop, nop, TS val 250 ecr 300>
+0.015 < S  0:0(0) win 65535 <mss 1460,nop,wscale 6,sackOK,TS val 100 ecr 0!>
+0.000 > S. ... ack 1 win 65535 <mss 1460,nop,wscale 4,sackOK,TS val ... ecr 100>
+0.035 < . 1:1(0) ack 1 win 1031 <nop, nop, TS val 150 ecr 200>
+0.000 > . 1:1(0) ack 1 win 12501 <nop, nop, TS val 200 ecr 150>
```

### CODE REVIEW

**Comment by tuexen** [comment]
I'm not sure, I understand completely, what you want to do...

The following script runs successfully on FreeBSD head, it is your script but some windows and window scaling values are adapted. Also the immediate ACK is not sent:
```
 0.000 socket(..., SOCK_STREAM, IPPROTO_TCP) = 3
+0.000 setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
+0.000 bind(3, ..., ...) = 0
+0.000 listen(3, 1) = 0
+0.100 < S  0:0(0) win 65535 <mss 1460,nop,wscale 6,sackOK,TS val 100 ecr 0>
+0.000 > S. 0:0(0) ack 1 win 65535 <mss 1460,nop,wscale 6,sackOK,TS val 200 ecr 100>
+0.050 < . 1:101(100) ack 1 win 1031 <nop, nop, TS val 150 ecr 200>
+0.000 accept(3, ..., ...) = 4
+0.000 read(4, ..., 100) = 100
+0.000 write(4, ..., 400) = 400
//+0.000 > . 1:1(0) ack 101 win 12495 <nop, nop, TS val 250 ecr 150>
+0.000 > P. 1:401(400) ack 101 win 1026 <nop, nop, TS val 250 ecr 150>
+0.050 < . 101:101(0) ack 401 win 1024 <nop, nop, TS val 200 ecr 250>
+0.000 < F. 101:101(0) ack 401 win 1031 <nop, nop, TS val 200 ecr 250>
+0.000 > . 401:401(0) ack 102 win 1026 <nop, nop, TS val 300 ecr 200>
+0.000 close(4) = 0
+0.000 > F. 401:401(0) ack 102 win 1026 <nop, nop, TS val 300 ecr 200>
+0.050 < . 102:102(0) ack 402 win 1031 <nop, nop, TS val 250 ecr 300>
+0.015 < S  0:0(0) win 65535 <mss 1460,nop,wscale 6,sackOK,TS val 100 ecr 0!>
+0.000 > S. 0:0(0) ack 1 win 65535 <mss 1460,nop,wscale 6,sackOK,TS val 200 ecr 100>
+0.035 < . 1:1(0) ack 1 win 1031 <nop, nop, TS val 150 ecr 200>
//+0.000 > . 1:1(0) ack 1 win 12501 <nop, nop, TS val 200 ecr 150>
```
So basically, you are establishing a TCP connection, tear it down via the `LAST-ACK` state and start over again. So why do you need the changes?

**Comment by tuexen** [comment]
Looking into the script a bit more detailed, the second `SYN-ACK` is only handled successfully, it the `TCP.SEG` is the same as in the original one. This is true as long as `SYN`-cookies are used. Using `sysctl -w net.inet.tcp.syncookies=0` results in a failure.

So I do see that you want to ignore part of the `SYN-ACK`, especially the `TCP.SEQ` and the `TS.val`.
I don't see why you want to ignore some fields of the injected `SYN`. Your patch also only modifies the handling of inbound packets, not outbound ones.

For ignoring the above fields in the outbound packets, I would prefer to reuse existing syntax like:
```
+0.000 > S. ...(0) ack 1 win 65535 <mss 1460,nop,wscale 6,sackOK,TS val ... ecr 100>
```
or
```
+0.000 > S. ... ack 1 win 65535 <mss 1460,nop,wscale 6,sackOK,TS val ... ecr 100>
```
or so. 
@jegglest: What do you think?

**Comment by jegglest** [comment]
Yes there is no reason to ignore any part of the SYN in this example. It is the SYN-ACK that needs to be ignored, I've modified the example. However that is generally because the test relates to an accept() instead of a connect(). I haven't tested it but I would assume that for a connect() based test with a duplicated and delayed SYN, the duplicate SYNs would need to be ignored for the same reasons.

**Comment by tuexen** [comment]
@jegglest When using a connect() based example, there would be no retransmissions of SYN segments once the connection is up. There can only be incoming SYN-ACK segments which arrive too late. But these segments would be inbound, not outbound. Or am I missing something?

**Comment by jegglest** [comment]
There can be a retransmitted or duplicated SYN that takes a different path and arrives late. Or maybe it's the retransmission we responded to and the original packet arrived late. It could also be something else entirely.

It sounds terrible but we saw some kind of traffic in Asia recently where packets were being duplicated and arriving at random unordered times relative to the original transmission receipt.

One theory was a network tap that, via misconfiguration, was connected to another part of the network and being routed normally. The delay from the tap and different path resulted in random arrival times between the original packet and the duplicate.

**Comment by jegglest** [comment]
Updated per your suggestions.

For sequence numbers, ... and ...(0) are semantically the same. The size of the packet and size of the tcp segment are always validated, if you want to ignore a packet with data then you'll have to specify the size of the payload: ...(100) for example.

If that doesn't meet your requirements let me know. size validations could be ignored if ... was specified but, I'm not sure that's a good idea.

**Pull request merged**
